greed/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    #custom urls
    path('user/', include('hotel.urls')),
    path('', include('greedhotel.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotel/urls.py
from django.urls import path
from hotel import views

app_name = "hotel"

urlpatterns = [

    path('signup/', views.RegisterView, name='signup'),
    path('login/', views.LoginView, name='login'),
    path('logout/', views.LogoutView, name='logout'),
    path('book/', views.BookingView, name='book'),
    path('profile/<user_id>', views.ProfileView, name='profile'),
    path('contactus/', views.ContactUsView, name='contactus'),
    path('aboutus/', views.AboutUsView, name='aboutus'),
    path('listbooking/', views.ListBooking, name='listbooking'),
    path('listreserve/', views.ListReserve, name='listreserve'),
    path('showbooking/<booking_id>', views.ShowBooking, name='showbooking'),
    path('showreserve/<booking_id>', views.ShowReserve, name='showreserve'),
    path('updatebooking/<booking_id>', views.UpdateBooking, name='updatebooking'),
    path('deletebooking/<booking_id>', views.DeleteBooking, name='deletebooking'),
    path('verify/', views.verify_view, name='verify-view'),
    path('verify2/', views.CodeVerify, name='verify2'),
    #path('login', views.login, name = 'login'),
    #path('register', views.register, name='register'),
    #path('home', views.home, name='home'),

]

hotel/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import CharField, Form, PasswordInput, ModelForm
from hotel.models import User, Reservation
from .models import Reservation, Code
from djmoney.forms.fields import MoneyField
import os

GENDER = (
    ("Female", "Female"),
    ("Male", "Male"),
    ("Other", "Other"),
)

ROOM_CHOICES = [
    ('Greed Hotel', 'Greed Hotel'),
    ('Room-only Hotel Rooms', 'Room-only Hotel Rooms'),
    ('Standard Hotel Rooms', 'Standard Hotel Rooms'),
    ('Minimalist Hotel Rooms', 'Minimalist Hotel Rooms'),
    ('Deluxe Hotel Rooms', 'Deluxe Hotel Rooms'),
    ('Standard Suite Rooms', 'Standard Suite Rooms'),
    ('Presidential Suites', 'Presidential Suites'),
    ('Penthouse Suites', 'Penthouse Suites'),
    ('Honeymoon Suites', 'Honeymoon Suites'),
]

IDENTITY_TYPE = (
    ("National ID Number", "National ID Number"),
    ("Driver's License", "Driver's License"),
    ("International Passport", "International Passport"),
)

def profile_id_upload_to(instance, filename):
    return f'profile_id/{filename}'

class ProfileForm(forms.ModelForm):

    full_name = forms.CharField(max_length=500)
    username = forms.CharField(max_length=500)
    email = forms.EmailField(max_length=500)
    phone = forms.CharField(max_length=100)
    gender = forms.ChoiceField(choices=GENDER, initial="Other")

    country = forms.CharField(max_length=100)
    city = forms.CharField(max_length=100)
    address = forms.CharField(max_length=1000)

    identity_type = forms.ChoiceField(choices=IDENTITY_TYPE)
    identity_image = forms.FileField()

    facebook = forms.URLField()
    twitter = forms.URLField()

    wallet = MoneyField(max_digits=12, decimal_places=2, default_currency='PHP', initial=0.00)

    class Meta:
        model = User
        fields = ['full_name', 'username', 'email', 'phone', 'gender', 'country', 'city', 'address', 'identity_type', 'facebook', 'twitter', 'wallet']

class BookingForm(ModelForm):
    username = forms.CharField(max_length=500)
    full_name = forms.CharField(max_length=500)
    email = forms.EmailField()
    phone = forms.CharField(max_length=100)
    room = forms.ChoiceField(choices=ROOM_CHOICES, initial='Greed Hotel')
    reservation_date = forms.DateTimeField(widget=forms.TextInput(attrs={'type': 'datetime-local'}))
    party_size = forms.IntegerField(widget=forms.TextInput(attrs={'type': "number", 'placeholder': "Person", 'min': "1"}))
    special_requests = forms.CharField()

    class Meta:
        model = Reservation
        fields = ['full_name', 'username', 'email', 'phone', 'room', 'reservation_date', 'party_size', 'special_requests']


class UserRegisterForm(UserCreationForm):

    full_name = forms.CharField(label=False, widget=forms.TextInput(attrs={'placeholder': "Full Name", 'class': "input-field"}))
    username = forms.CharField(label=False, widget=forms.TextInput(attrs={'placeholder': "Username", 'class': "input-field"}))
    email = forms.EmailField(label=False, widget=forms.TextInput(attrs={'placeholder': "Email", 'class': "input-field"}))
    phone = forms.CharField(label=False, widget=forms.TextInput(attrs={'placeholder': "Phone", 'class': "input-field"}))
    password1 = forms.CharField(label=False, widget=forms.PasswordInput(attrs={'placeholder': "Password", 'class': "input-field"}))
    password2 = forms.CharField(label=False, widget=forms.PasswordInput(attrs={'placeholder': "Confirm Password", 'class': "input-field"}))

    class Meta:
        model = User
        fields = ['full_name', 'username', 'email', 'phone', 'password1', 'password2']


class UserLoginForm(AuthenticationForm):

    username = forms.CharField(widget=forms.TextInput(attrs={'type': "email", 'placeholder': "Email", 'class': "input-field"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'type': "password", 'placeholder': "Password", 'class': "input-field"}))

    class Meta:
        fields = ['username', 'password']


class CodeForm(forms.ModelForm):
    number = forms.CharField(label=False, widget=forms.TextInput(attrs={'placeholder': "Enter Verification Code", 'class': "input-field"}))
    class Meta:
        model = Code
        fields = ['number'] 
        
class CodeForm2(forms.ModelForm):
    username = forms.CharField(label=False, widget=forms.TextInput(attrs={'placeholder': "Username", 'class': "input-field"}))

    number = forms.CharField(label=False, widget=forms.TextInput(attrs={'placeholder': "Enter Verification Code", 'class': "input-field"}))
    class Meta:
        model = Code
        fields = ['username', 'number'] 

class Approval(forms.ModelForm):
    
    class Meta(Reservation):
        model = Reservation
        fields = ['approval_status', 'approval_comment']

hotel/views.py
from django.shortcuts import render, redirect
from hotel.models import User, Reservation, ContactUs, Room, Code
from hotel.forms import UserRegisterForm, UserLoginForm, BookingForm, CodeForm, CodeForm2, Approval
from django.utils import timezone
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages, auth
import re
from datetime import datetime, date
from django.core.mail import send_mail
from django.conf import settings
from greed import settings
from djmoney.money import Money

@login_required(login_url='/user/login/')
def CodeVerify(request):

    form = CodeForm2(request.POST or None)

    id = request.user.id

    code = Code.objects.filter(user=id)

    code = code.first()
    
    if request.method == "POST":
        if 'displayCodeBtn' in request.POST:
            
            messages.success(request, f'Your Code: {code}')

        else:
            if form.is_valid():
                
                username = form.cleaned_data.get('username')
                num = form.cleaned_data.get('number')

                try:
                    user = User.objects.get(username=username)
                except User.DoesNotExist:
                    user = None

                if user is not None:
                    stored_code = user.code

                    if str(stored_code) == num:
                        user.verified = True
                        user.guest = False
                        user.save()
                        messages.success(request, f"{user.full_name}, you are now verified.")
                        return redirect('greedhotel:home')
                    else:
                        messages.error(request, "Invalid Verification Code")
                else:
                    messages.error(request, "User not found with the provided username")
    return render(request, "userauth/verify2.html", {'form': form})

def ContactUsView(request):

    

    if request.method == "POST":
        contact=ContactUs()
        name = request.POST.get('name')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')

        contact.name=name
        contact.email=email
        contact.subject=subject
        contact.message=message

        contact.save()
        messages.success(request, f"Thank you for your feedback.")
        return redirect('greedhotel:home')

    return render(request, 'hotel/contactus.html')

@login_required(login_url='/user/login/')
def LogoutView(request):
    logout(request)
    return redirect("greedhotel:home")

def LoginView(request):

    form = UserLoginForm(request.POST or None)

    context = {
        "form":form,
    }

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            if user.verified == True:
                auth.login(request, user)
                return redirect("greedhotel:home")
            else:
                auth.login(request, user)
                if user.guest == True:
                    messages.error(request, f"{user.full_name}, you still have a GUEST account because it has not been verified yet.")
                    return redirect("greedhotel:home")
                else:
                    messages.error(request, f"{user.full_name}, your account has not been verified yet.")
                    return redirect("greedhotel:home")
        else:
            messages.error(request, "Invalid login details.")
    return render(request, "userauth/authlog.html", context)

def RegisterView(request):
    if request.user.is_authenticated:
        messages.warning(request, f"You are already logged in.")
        return redirect("greedhotel:home")

    if request.method =="POST":
        form = UserRegisterForm(request.POST or None)

        if form.is_valid():
            print("Success")
            form.save()
            full_name = form.cleaned_data.get("full_name")
            username = form.cleaned_data.get("username")
            email = form.cleaned_data.get("email")
            phone = form.cleaned_data.get("phone")
            password = form.cleaned_data.get("password1")

            user = authenticate(email=email, password=password)

            messages.success(request, f"Hey {full_name}, we need your verification code to complete your registration.")

            if user is not None:
                request.session['pk'] = user.pk
                return redirect("hotel:verify-view")
    else:
        form = UserRegisterForm()

    context = {
        "form":form,
    }

    return render(request, "userauth/authreg.html", context)

def verify_view(request):
    form = CodeForm(request.POST or None)
    pk = request.session.get('pk')
    if pk:
        user = User.objects.get(pk=pk)
        email = user.email
        code = user.code
        sender = 'isoygwapo84@gmail.com'
        code_user = f"{user.username}: {user.code}"
        subject = "[Greed's Hotel] Verification Code"

        message = f'The code is required for further verification if you want to verify your account. To complete the registration, enter the verification code provided. \n\n\nVerification Code: {code}'

        # Use a list or tuple for the "to" argument
        recipient_list = [email]

        send_mail(subject, message, sender, recipient_list)
        
        if not request.POST:
            print(code_user, email) 
            #send SMS code
        if form.is_valid():
            num = form.cleaned_data.get('number')
            
            if str(code) == num:
                user.verified = True
                user.guest = False
                user.save()
                code.save()
                if user is not None:
                    request.session['pk'] = user.pk
                    messages.success(request, f"{user.full_name}, you are now verified.")
                    return redirect('hotel:login')
            else:
                messages.error(request, "Invalid Verification Code")
    return render(request, "userauth/verify.html", {'form': form})

def deduction_room_price(room, money):
    if room == "Room-Only Hotel Rooms":
        price = Money(7500, 'PHP') 
        return money - price
    elif room == "Standard Hotel Rooms":
        price = Money(12500, 'PHP')
        return money - price
    elif room == "Minimalist Hotel Rooms":
        price = Money(10000, 'PHP')
        return money - price
    elif room == "Deluxe Hotel Rooms":
        price = Money(20000, 'PHP')
        return money - price
    elif room == "Standard Suite Rooms":
        price = Money(25000, 'PHP')
        return money - price
    elif room == "Presidential Suites":
        price = Money(100000, 'PHP')
        return money - price
    elif room == "Penthouse Suites":
        price = Money(150000, 'PHP')
        return money - price
    elif room == "Honeymoon Suites":
        price = Money(25000, 'PHP')
        return money - price
    
def decline_room_price(room, money):
    if room == "Room-Only Hotel Rooms":
        price = Money(7500, 'PHP')  
        return money + price
    elif room == "Standard Hotel Rooms":
        price = Money(12500, 'PHP')
        return money + price
    elif room == "Minimalist Hotel Rooms":
        price = Money(10000, 'PHP')
        return money + price
    elif room == "Deluxe Hotel Rooms":
        price = Money(20000, 'PHP')
        return money + price
    elif room == "Standard Suite Rooms":
        price = Money(25000, 'PHP')
        return money + price
    elif room == "Presidential Suites":
        price = Money(100000, 'PHP')
        return money + price
    elif room == "Penthouse Suites":
        price = Money(150000, 'PHP')
        return money + price
    elif room == "Honeymoon Suites":
        price = Money(25000, 'PHP')
        return money + price

def get_price(room):
    if room == "Room-Only Hotel Rooms":
        price = Money(7500, 'PHP')
        return price
    elif room == "Standard Hotel Rooms":
        price = Money(12500, 'PHP')
        return price
    elif room == "Minimalist Hotel Rooms":
        price = Money(10000, 'PHP')
        return price
    elif room == "Deluxe Hotel Rooms":
        price = Money(20000, 'PHP')
        return price
    elif room == "Standard Suite Rooms":
        price = Money(25000, 'PHP')
        return price
    elif room == "Presidential Suites":
        price = Money(100000, 'PHP')
        return price
    elif room == "Penthouse Suites":
        price = Money(150000, 'PHP')
        return price
    elif room == "Honeymoon Suites":
        price = Money(25000, 'PHP')
        return price

@login_required(login_url='/user/login/')
def ShowReserve(request, booking_id):
    reservations_show = Reservation.objects.get(pk=booking_id) 
    
    form = Approval(request.POST or None, instance=reservations_show)
    if request.method == 'POST':
        status = request.POST.get('approval_status')
        comment = request.POST.get('approval_comment')

        if status == "approved" or status == "declined":
            if status == "approved":
                id = request.POST.get('reservation_id')
                print(id)
                Reservation.objects.filter(booking_number=id).update(approval_status=True)
                Reservation.objects.filter(booking_number=id).update(checked=True)
                Reservation.objects.filter(booking_number=id).update(approval_comment=comment)
                return redirect('hotel:listreserve')

templates/hotel/aboutus.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'css/aboutus.css' %}">
<style>
    h2 {
        margin-left: 100px;
    }
    #testimonials {
        margin-top: 30px;
    }
    .testimonial {
        margin-left: 100px;
        margin-right: 30px;
    }
</style>
<img class="greed" src="{% static 'img/logo.png' %}" alt="greed">
<section id="about-info" class="bg-light py-3">
    <div class="container">
        <div class="info-left">
            <h1 class="l-heading"><span class="=testimonial bg-primar">About </span>Greed's Hotel</h1><br>
            <p>Greed's Hotel in Argao, Cebu, Philippines, was founded by Celso M. Puerto Jr. and Maria Zyma Saphy Legaspi Quipao in 1995. Situated on a hill, the hotel offered stunning views of the Bohol Strait. Combining modern comfort with Filipino cultural elements, the hotel became popular for its hospitality and commitment to showcasing the local heritage. </p><br>
            <p>
            Greed's Hotel in Argao, Cebu, Philippines, was founded by Celso M. Puerto Jr. and Maria Zyma Saphy Legaspi Quipao in 1995.
            </p>
        </div>
        <div class="info-right">
{#            <img src="{% static 'img/background.png' %}" alt="hotel">#}
        </div>
    </div>
</section>

<div class="clr"></div>

<section id="testimonials" class="py-3">
    <div class="container">
        <h2 class="l-heading">Our Proud Clients</h2>
        <div class="testimonial bg-primary">
            <img src="{% static 'img/19.jpg' %}" alt="celso">
            <p>Hi, I'm Ali a dynamic individual passionate about computers, games, and music. I thrive on exploring and finding new things to do with the help of God our father who arth in heaven, believe in continuous growth, and am eager to connect and explore new opportunities. Let's engage!</p>
        </div>

        <div class="testimonial bg-primary">
            <img src="{% static 'img/19.jpg' %}" alt="zyma">
            <p>Hello, I'm Royal a motivated individual with a keen interest in singing, art, cooking, and sleeping. Whether I'm engaged in work, pursuing hobbies, or any other relevant activities, I bring enthusiasm and a commitment to excellence. Eager to connect and discover new possibilities!</p>
        </div>
    </div>
</section>
<script>
    var greedLogo = document.querySelector('.greed');
    var lastScrollTop = 0;

    window.addEventListener("scroll", function() {
        var scrollTop = window.scrollY || document.documentElement.scrollTop;

        if (scrollTop > lastScrollTop) {
        // Scrolling down
            greedLogo.style.opacity = "0";
        } else {
        // Scrolling up
            greedLogo.style.opacity = "1";
        }

        
    });
</script>
{% endblock content %}

templates/hotel/home.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
<html lang="en">
<head>
    <meta http-equiv"X-UA-Compatible" content="ie=edge">
    <meta name="description" content="Welcome to Greed's Hotel in Cebu Philippines">
    <meta name="keywords" content="hotel, cebu hotel, philippines hotel">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <title>Greed's Hotel Management | Welcome</title>
</head>
<body>
    <header>
    <div id="showcase">
      <div class="container">
        <div class="showcase-content">
          <p class="lead"> Welcome to the best hotel in the Philippines. Looking for a place to stay? Book now!</p>
          <h1>Enjoy Your <span class="text-primary">Stay</span></h1>
          <a class="btn" href="{% url 'hotel:book' %}">Book Now</a>
        </div>
    </div>
</div>
</header>

<section id="home-info" class="bg-dark">
  <div class="info-img"></div>
  <div class="info-content">
    <h2><span class="text-primary">Greed's Hotel History</span>Of Our Hotel</h2>
    <p> Greed's Hotel Management, established in the vibrant 1990s, is a luxurious haven located in Argao, Cebu. With a fusion of traditional Filipino charm and modern comforts, the hotel offers a serene escape amidst picturesque landscapes. Its opulent suites, gourmet restaurant, spa, and outdoor pool create a lavish experience. The dedicated staff ensures personalized service, making it a top choice for leisure and business travelers alike. As a symbol of luxury, Greed's Hotel Management continues to be celebrated as one of the finest establishments in the Philippines, beckoning guests to indulge in a timeless blend of hospitality and sophistication. </p>
    <a href="aboutus.html" class="btn btn-light">Read More</a>
  </div>
</section>

<section id="features">
  <div class="box bg-light">
    <i class="fas fa-hotel fa-3x"></i>
    <h3>Location</h3>
    <p>Suba, Argao, Cebu</p>
</div>
  <div class="box bg-primary">
    <i class="fas fa-utensils fa-3x"></i>
  <h3>Free Meals</h3>
    <p>King Crab, Lobster, Wagyu Steak</p>
</div>
  <div class="box bg-light">
    <i class="fas fa-dumbbell fa-3x"></i>
  <h3>Fitness Room</h3>
    <p>Gym all day everyday</p>
</div>
</section>

<div class="clr"></div>

<footer id="main-footer">
  <p> Greed's Hotel Management &copy; 2023, All Rights Reserved</p>
</footer>
</body>
</html>

{% endblock content %}

templates/hotel/index.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'css/style.css' %}" />
  


{% endblock content %}

templates/hotel/listbooking.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}

<style>
    * {
        color: white;
    }
    .banner {
        padding-left: 75px;
    }
    td{
        font-family: 'poppins', sans-serif;
        font-weight: 40;
    }
    th{
        font-weight: 100;
        text-transform: uppercase;
        font-size: 1.1em;
    }
    td a{
        font-weight: 100;
    }
    h1{
        font-weight: 100;
    }
</style>

<link rel="stylesheet" href="{% static 'css/table.css' %}"/>
<script src="{% static 'js/table.js' %}"></script>


    <main class="table">
        <section class="table__header">
            <h1>My Booking List</h1>

            <div class="export__file">
                <label for="export-file" class="export__file-btn" 
            </div>
        </section>
        <section class="table__body">
            <table>
                <thead>
                    <tr>
                        <th> Id <span class="icon-arrow">&UpArrow;</span></th>
                        <th> Customer <span class="icon-arrow">&UpArrow;</span></th>
                        <th> Update <span class="icon-arrow">&UpArrow;</span></th>
                        <th> Delete <span class="icon-arrow">&UpArrow;</span></th>
                    </tr>
                </thead>
                <tbody>
                    {% for reservation in reservations_list %}
                        {% if reservation.full_name == user.full_name %}
                            <tr>
                                <td> {{ reservation.booking_number }} </td>
                                <td> <a href="{% url 'hotel:showbooking' reservation.id %}">{{ reservation.full_name }} </a></td>
                                {% if reservation.approval_status == True %}
                                    <td> <a href="{% url 'hotel:showbooking' reservation.id %}">Approved </a></td></td>
                                    <td> <p>Not Deletable</p></td>
                                {% else %}
                                    {% if reservation.checked == True %}
                                        <td> <a href="{% url 'hotel:showbooking' reservation.id %}">Declined</a></td>
                                        <td> <p>Not Deletable</p></td>
                                    {% else %}
                                        <td> <a href="{% url 'hotel:updatebooking' reservation.id %}">Update</a></td>
                                        <td> <a href="{% url 'hotel:deletebooking' reservation.id %}">Delete</a></td>
                                    {% endif %}
                                {% endif %}

                            </tr>
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </section>
    </main>

{% endblock content %}

templates/hotel/listreserve.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}

<style>
    * {
        color: white;
    }
    .banner {
        padding-left: 75px;
    }
    td{
        font-family: 'poppins', sans-serif;
        font-weight: 40;
    }
    th{
        font-weight: 100;
        text-transform: uppercase;
        font-size: 1.1em;
    }
    td a{
        font-weight: 100;
    }
    h1{
        font-weight: 100;
    }
</style>

<link rel="stylesheet" href="{% static 'css/table.css' %}"/>
<script src="{% static 'js/table.js' %}"></script>


    <main class="table">
        <section class="table__header">
            <h1>Reservation List</h1>

            <div class="export__file">
                <label for="export-file" class="export__file-btn" 
            </div>
        </section>
        <section class="table__body">
            <table>
                <thead>
                    <tr>
                        <th> Id <span class="icon-arrow">&UpArrow;</span></th>
                        <th> Customer <span class="icon-arrow">&UpArrow;</span></th>
                    </tr>
                </thead>
                <tbody>
                    {% for reservation in reservations_list %}
                        {% if reservation.checked == False %}
                            <tr>
                                <td> {{ reservation.booking_number }} </td>
                                <td> <a href="{% url 'hotel:showreserve' reservation.id %}">{{ reservation.full_name }} </a></td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </section>
    </main>

{% endblock content %}

templates/hotel/showbooking.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}



<style>
    * {
        color: rgb(255, 255, 255);
    }
    .banner {
        padding-left: 75px;
    }
    body{

        padding: 80px 300px 0 300px;
    }
    h1{
        padding: 200px 0 0 0;
        color: #ffffff;
    }
    .move{
        margin-top: 50px;
        margin-bottom: 50px;
        color: #000000;
    }
    .celso {
        font-size: 0.875rem;
        text-transform: uppercase;
        color:#ffffff;
        border-radius: 50px;
        background-color: rgba(0, 0, 0, 0.445);
        display: flex;
        position: relative;
        align-content: center;
        justify-content: center;
    }
    .card-header{
        font-size: 20px;
    }
</style>
<div class="move">
    <div class="card text-white bg-primary mb-3" style="max-width: 100%;">
        <div class="card-header">{{ reservations_show }} - Details</div>
        <br/>
        <div class="card-body">
        <h4 class="card-title">ID: {{ reservations_show.booking_number }}</h4>
        <p class="card-text">Full Name: {{ reservations_show.full_name }}</p>
        <p class="card-text">Username: {{ reservations_show.username }}</p>
        <p class="card-text">Email: {{ reservations_show.email }}</p>
        <p class="card-text">Phone: {{ reservations_show.phone }}</p>
        <p class="card-text">Room: {{ reservations_show.room }}</p>
        <p class="card-text">People: {{ reservations_show.party_size }}</p>
        <p class="card-text">Check-In: {{ reservations_show.reservation_date }}</p>
        <p class="card-text">Check-Out: {{ reservations_show.reservation_date_out }}</p>
        <p class="card-text">Special Requests: {{ reservations_show.special_requests }}</p>
        <p class="card-text">Wallet: {{ reservations_show.wallet }}</p>
        <p class="card-text">Price: {{ reservations_show.price }}</p>
        <p class="card-text">Change: {{ reservations_show.change }}</p>
        {% if reservations_show.approval_status == True %}
            <p class="card-text">Approval Status: Approved</p>
            <p class="card-text">Admin Comment: {{ reservations_show.approval_comment }}</p>
        {% elif reservations_show.checked == False %}
            <p class="card-text">Approval Status: Pending</p>
        {% else %}
            <p class="card-text">Approval Status: Declined</p>
            <p class="card-text">Admin Comment: {{ reservations_show.approval_comment }}</p>
        {% endif %}
        <br>
        <a href="{% url 'hotel:listbooking' %}" class="celso">GO BACK</button>
        </div>
    </div>
</div>
    <center>
        <h1></h1>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
       
    </center>

{% endblock content %}

templates/hotel/updatebooking2.html
{% extends 'partials/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<style>
    * {
        color: rgb(255, 255, 255);
    }
    .banner {
        padding-left: 75px;
        background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)),url('../../img/snow.gif') cover;
    }
    body{
        background-color: black;
        padding: 0 500px 0 500px;
    }
    h1{
        padding: 200px 0 0 0;
        color: #ffffff;
    }
    button{
        width: 100%;
    }
</style>

    <h1>Update Booking</h1>
    <form method="POST">
        {% csrf_token %}

        {{form.full_name|as_crispy_field}}
        <br/>

        {{form.username|as_crispy_field}}
        <br/>

        {{form.email|as_crispy_field}}
        <br/>

        {{form.phone|as_crispy_field}}
        <br/>

        {{form.room|as_crispy_field}}
        <br/>

        {{form.party_size|as_crispy_field}}
        <br/>

        {{form.reservation_date|as_crispy_field}}
        <br/>
        
        <input type="hidden" name="reservation_id" value="{{ reservation_update.booking_number }}"/>
        <input type="hidden" class="prevroom" id="prevroom" name="prevroom" value="{{ reservation_update.room }}"/>

        {{form.special_requests|as_crispy_field}}

        <br/>
        <br/>
        <button type="submit" class="btn btn-lg btn-primary">UPDATE</button>
    </form>
    <br/>
    <br/>        
    <br/>
    <br/>

{% endblock content %}